// Generated by CoffeeScript 1.8.0
var assert, jsforce, sfdeploy;

sfdeploy = require("../sfdeploy");

jsforce = require("jsforce");

assert = require("assert");

describe("Deploy", function() {
  this.timeout(160000);
  return describe('#deploy()', function() {
    return it('should deploy some junk', function(done) {
      var conn;
      conn = new jsforce.Connection({
        loginUrl: 'https://login.salesforce.com',
        version: '31.0'
      });
      return conn.login('daniel@3demo.com', 'silverforc3qLVOLQ9udUSYszsc76Mrc9Acd', (function(_this) {
        return function(er, data) {
          var deploy;
          deploy = new sfdeploy(__dirname, [], conn, '31.0', {
            runPackagedTestsOnly: true,
            checkOnly: true
          });
          return deploy.deploy([], function(er, data) {
            console.log(data);
            return done();
          });
        };
      })(this));
    });
  });
});
